services:

  # ── 1. Backend FastAPI (Prédiction) ─────────────────────────────────────────
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # SÉCURITÉ : On retire "ports:" pour éviter de contourner Nginx.
    # Les conteneurs se parlent en interne. Nginx le trouvera sur le port 80.
    expose:
      - "80"
    volumes:
      - ./data/users.json:/app/data/users.json
      - ./data/predictions_log.jsonl:/app/data/predictions_log.jsonl
      - ./models:/app/models

  # ── 2. Reverse proxy Nginx ─────────────────────────────────────────────────
  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Ton point d'entrée unique pour le web/frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      # CORRECTIF : On supprime "training-api" d'ici pour éviter que Docker ne bloque au démarrage.

  # ── 3. Interface Streamlit ─────────────────────────────────────────────────
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./models:/app/models:ro
    depends_on:
      - nginx

  # ── 4. MLflow Tracking Server ──────────────────────────────────────────────
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    profiles:
      - training
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri /mlflow/mlruns
        --default-artifact-root /mlflow/artifacts

  # ── 4b. MLflow Webhook Worker (Le webhook qui pousse les modèles en PROD sur DagsHub) ────────
  mlflow-webhook-worker:
    image: python:3.10-slim
    profiles:
      - training
    volumes:
      # On injecte notre script directement dans une image python de base !
      - ./mlflow_extensions:/app
      # On partage le dossier mlflow pour que le script lise les artefacts rapidement
      - ./mlflow:/mlflow 
    working_dir: /app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    command: sh -c "pip install fastapi uvicorn boto3 mlflow && uvicorn webhook_handler:app --host 0.0.0.0 --port 8000"
    depends_on:
      - mlflow

  
  # ── 5. Training API ────────────────────────────────────────────────────────
  training-api:
    build:
      context: .
      dockerfile: training/Dockerfile
    profiles:
      - training
    # SÉCURITÉ : Plus besoin d'exposer le port 8001 au public. Nginx s'en charge en interne sur le port 8000.
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - GIT_USER=${GIT_USER}
      - GIT_TOKEN=${GIT_TOKEN}
    depends_on:
      - mlflow